# Site settings
title: Open FPGA NVM
email: gieseo.park@utdallas.edu
description: > # this means to ignore newlines until "baseurl:"
 Open FPGA NVM is open sourced characterization platform for evaluating real NVM devices(e.g. MRAM, PCM, RRAM, TLC/MLC/SLC NAND flashs, etc.).
 Contribution is always welcomed.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: kisuo
#facebook_username: kisuo
github_username:  open-fpga-nvm

# Build settings
markdown: kramdown
