# Site settings
title: Open-NVM
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  open-fpga-nvm

# Build settings
markdown: kramdown
